buildContainer:
  tool:
    docker:
      file: Docker/Dockerfile
      imageTag: 1.3

publishArtifact:
  release: true

deployList:
  repeatableSets:
    - deploySet:
        conciergeCheck:
          environment: sit # sit, qa, prod
          artifact:
            name: omn/karina
            version: 1.3
          tenant: C0 # IT: C0, DE: HV, AT: BA
          configurations:
            - OMN BE SIT ENV
        # dbMigrations:
        #   tool:
        #     liquibase:
        #       changeLogFile: sql-scripts/changelog-master.xml
        #       command: update
        #       credentialsId: sit-postgres-it-customer-digitalization
        #       clientCerts: [it_sit_client_cert, it_sit_server_ca, it_sit_client_key]
        #       driver: org.postgresql.Driver
        #       globalOptions: --logLevel=debug --contexts=C0
        #       url: jdbc:postgresql://db.pgsql.it.omn.sit.g4c.unicredit.eu/it-customer-digitalization?ssl=true&sslmode=verify-ca&sslcert=${it_sit_client_cert}&sslkey=${it_sit_client_key}&sslrootcert=${it_sit_server_ca}
        #       artifacts:
        #         - repositoryPath: maven-group/org/postgresql/postgresql/42.2.20/postgresql-42.2.20.jar
        #         - repositoryPath: maven-group/eu/unicredit/wep/liquibase-filters/1.0.1-RELEASE/liquibase-filters-1.0.1-RELEASE.jar
        install:
          tool:
            helm:
              path: helm/karina
              values: helm/karina/values-sit.yaml
              releaseName: karina-sit
              uninstallOnFailure: true
        label: SIT
