
{{- $annotations := include "karina.annotations" . -}}
{{- range $secret := .Values.secrets }}
{{- if .createExternalSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.app.namespace }}
  annotations:
    {{ $annotations | nindent 4 }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: {{ .projectId }}           # Deve essere il NOME del ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .name }}                # <-- forza il nome del Secret K8s generato
    creationPolicy: Owner
  # template:                        # Optional, usa solo se previsto dal KES
  #   metadata: {}
  #   type: kubernetes.io/tls
  data:
    {{- range .properties }}
    - secretKey: {{ .keyRef }}       # Chiave nel Secret K8s
      remoteRef:
        {{- if .isBinary }}
        decodingStrategy: Base64     # Usa solo se in KES la chiave è binaria
        {{- end }}
        key: {{ $secret.credentialName }}   # Nome del Secret in GCP Secret Manager
        property: {{ .keyRef }}             # Chiave JSON dentro al Secret GCP
        version: latest
    {{- end }}
---
{{- end }}
{{- end }}
