apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "karina.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "karina.selectorLabels" . | nindent 4 }}
